when:
  - event: [pull_request, tag]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
      - renovate/*

variables:
  - &buildx_plugin 'docker.io/woodpeckerci/plugin-docker-buildx:3.1.0'
  - &platforms_alpine 'linux/arm/v7,linux/arm64/v8,linux/amd64'
  - publish_logins: &publish_logins
      - registry: https://index.docker.io/v1/
        username: ch1ch1
        password:
          from_secret: docker_token
  - &publish_repos 'ch1ch1/drone-hugo'

steps:
  build-drone-hugo-dev:
    image: *buildx_plugin
    settings:
      repo: *publish_repos
      dockerfile: Dockerfile
      platforms: *platforms_alpine
      tag: latest-dev
      logins: *publish_logins
    when:
      - event: [pull_request, push]

  build-drone-hugo:
    image: *buildx_plugin
    settings:
      repo: *publish_repos
      dockerfile: Dockerfile
      platforms: *platforms_alpine
      tag: [latest, 'hugo_${CI_COMMIT_TAG}_alpine_ci_plugin']
      logins: *publish_logins
    when:
      - event: tag